name: yeah_music
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hooks_riverpod: ^2.5.1
  just_audio: ^0.9.42
  audio_session: ^0.1.18
  on_audio_query: ^2.9.0
  permission_handler: ^11.3.1
  just_audio_background: ^0.0.1-beta.12
  file_picker: ^8.0.6   # 用来选择目录或文件

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
