name: yeah_music
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.8
  hooks_riverpod: 2.6.1
  just_audio: 0.10.5
  just_audio_media_kit: 2.1.0 # liunx 需要加入这个插件才能支持音乐播放
  audio_session: 0.2.2
  permission_handler: 12.0.1
  just_audio_background: 0.0.1-beta.17
  file_picker: 10.3.2  # 用来选择目录或文件
  #  ffmpeg_kit_flutter_new: 3.2.0
  audio_metadata_reader: 1.4.2 # 读取歌曲元数据
  tray_manager: 0.5.1 # 控制托盘图标
  logger: 2.6.1
  ffi: 2.1.4
  hive: 2.2.3 # 结构化存储，比 shared_preferences 更灵活
  hive_flutter: 1.1.0 # Flutter 专用的封装层
  provider: ^6.1.5+1 # 状态管理包
  charset: ^2.0.1 # 字符集
#  disk_space_2: ^1.0.10 # 获取磁盘信息
#  system_info2: ^4.0.0 # 读取系统信息
  intl: ^0.20.2 # 提供国际化和本地化设施，包括消息翻译、复数和性别、日期/数字格式和解析以及双向文本。
#  url_launcher: ^6.3.2 # 用于启动 URL 的 Flutter 插件
  device_info_plus: ^11.5.0 # 获取设备信息
  palette_generator: ^0.3.3+4 # 从图片提取颜色调色板
  shared_preferences: ^2.3.5 # 本地存储
  image_picker: ^1.1.2 # 图片选择器
  path_provider: ^2.1.5 # 沙箱内持久路径（主题背景图缓存）
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0
  flutter_launcher_icons: ^0.14.4 # 图标生成
  build_runner: ^2.4.12 #  生成 Hive TypeAdapter： flutter packages pub run build_runner build   或者 dart run build_runner build --delete-conflicting-outputs
  hive_generator: ^2.0.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/yeah_music.png" # 生成图标命令：flutter pub run flutter_launcher_icons:main

flutter:
  uses-material-design: true
  assets: # 注册资源
    - assets/icons/
