name: yeah_music
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.8
  hooks_riverpod: 2.6.1
  just_audio: 0.10.4
  audio_session: 0.2.2
  on_audio_query: 2.9.0
  permission_handler: 12.0.1
  just_audio_background: 0.0.1-beta.17
  file_picker: 10.3.2  # 用来选择目录或文件

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0

flutter:
  uses-material-design: true
