org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
#android.useAndroidX=true
#android.enableJetifier=true
# ?? Gradle ?????????????? JVM
org.gradle.daemon=true
#org.gradle.jvmargs=--add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.ref=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED
# JVM ???????????????
# ??????????? CPU
org.gradle.parallel=true

# ??????????????
org.gradle.caching=true

# ?? Gradle ????????????Gradle 6.8+ ???
org.gradle.configuration-cache=false
org.gradle.unsafe.configuration-cache=false

# ????????????????
systemProp.gradle.checksums.insecure=true

## ==============================
## ? ??????
## ==============================

# ???????????????
org.gradle.offline=false

# ?????? JDK?????????? JDK ???
# ubuntu
#org.gradle.java.home=/usr/lib/jvm/temurin-17-jdk-amd64
# MacOS
org.gradle.java.home=/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home

## ==============================
## ? ??/????
## ==============================

# ?????????info/debug ?????
org.gradle.logging.level=info

# Android ??????????????
android.useAndroidX=true
android.enableJetifier=false
# ?? PNG crunch???????????????????
android.enableResourceOptimizations=false

